require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "spec/fixtures/**/*"
    - "vendor/**/*"
    - "tmp/**/*"

Layout/LineLength:
  Max: 120

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  Max: 250

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 12

Metrics/ParameterLists:
  CountKeywordArgs: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/DescribeClass:
  Exclude:
    - "spec/integration/**/*"
    - "spec/contract/**/*"
